[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 1000000
via_ir = true
ffi = true

# Fhenix specific configuration
[profile.fhenix]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true
